version: "3.4"

x-services: &env
  env_file:
    - ${ENV:-testnet}.env

services:
  backend:
    <<: *env
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - NEAR_EXPLORER_PUBSUB_PORT=8080
    mem_limit: 1G
    entrypoint: ["npm", "run", "start"]
    ports:
      - 10000:8080

  frontend:
    <<: *env
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - PORT=3000
      - NEAR_EXPLORER_PUBSUB_HOST=localhost
      - NEAR_EXPLORER_PUBSUB_SECURE=false
      - NEAR_EXPLORER_PUBSUB_PORT=10000
    ports:
      - 3000:3000
    command: ["npm", "run", "start"]
